### ISSUE TITLE
After some time volume is no more available to pod: Socket not connected

### ISSUE THREAD

**Issue by jmaitrehenry** [kubernetes-sigs/blobfuse-csi-driver#173]
**What happened**:
After some time, the volume is no more accessible for the pod.
In the StatefulSet, the first pod doesn't have any issue 40d later, the second pod is broken after 48 days, can't say if it's a problem that occur after a fixed time or not.

From Redis using the volume for the dump.rdb file:
```
Failed opening the RDB file dump.rdb (in server root dir /data) for saving: Socket not connected
```

From kubectl trying to enter in the container where the volume is the cwd:
```
❯ kubectl --context=aks exec -ti  -n redis redis-0 ash
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "chdir to cwd (\"/data\") set in config.json failed: transport endpoint is not connected": unknown
```

**What you expected to happen**:
The volume is still accessible.

**How to reproduce it**:
Have a pod with a volume and wait.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: mcr.microsoft.com/k8s/csi/blobfuse-csi:v0.4.0
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"2b13e288f94dd2577d4ff7261f9eb76b1d5692a1", GitTreeState:"clean", BuildDate:"2020-06-01T21:55:34Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release): AKS
- Kernel (e.g. `uname -a`): `Linux redis-1 4.15.0-1082-azure #92~16.04.1-Ubuntu SMP Tue Apr 14 22:28:34 UTC 2020 x86_64 Linux`
- Others: 
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage
provisioner: blobfuse.csi.azure.com
parameters:
  skuName: Standard_LRS
  resourceGroup: infra
  storageAccount: xxx
reclaimPolicy: Retain  # if set as "Delete" container would be removed after pvc deletion
volumeBindingMode: Immediate
mountOptions: 
  - -o gid=1000
  - -o uid=999
  - -o allow_other
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        agentpool: "memoptimized"
      containers:
        - name: redis
		  [...]
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        storageClassName: redis-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
```
