### ISSUE TITLE
OWNERS and OWNERS_ALIASES files are invalid and causing errors.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes-sigs/blobfuse-csi-driver#83]
1) The OWNERS_ALIASES file isn't a valid format and doesn't parse at all.
```yaml
{
  base: "master"   
  client: "repoowners"   
  component: "hook"   
  error: "error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field .aliases of type map[string][]string"   
  file: "prow/repoowners/repoowners.go:349"   
  func: "k8s.io/test-infra/prow/repoowners.loadAliasesFrom"   
  level: "error"   
  msg: "Failed to unmarshal aliases from "/tmp/git558231759/OWNERS_ALIASES". Using empty alias map."   
  org: "kubernetes-sigs"   
  repo: "blobfuse-csi-driver"   
}
```
Here is an example of a valid OWNERS_ALIASES file: https://github.com/kubernetes/test-infra/blob/master/OWNERS_ALIASES

2) The OWNERS file only includes @andyzhangx which makes it impossible to approve a PR authored by @andyzhangx.  e.g. This PR (https://github.com/kubernetes-sigs/blobfuse-csi-driver/pull/82) had to be manually merged instead of letting Tide merge it as is policy.
```yaml
{
  author: "andyzhangx"   
  component: "hook"   
  event-GUID: "e3731080-20c0-11ea-9a5f-9d203b6a99db"   
  event-type: "pull_request"   
  file: "prow/plugins/blunderbuss/blunderbuss.go:238"   
  func: "k8s.io/test-infra/prow/plugins/blunderbuss.handle"   
  level: "warning"   
  msg: "Not enough reviewers found in OWNERS files for files touched by this PR. 0/2 reviewers found."   
  org: "kubernetes-sigs"   
  plugin: "blunderbuss"   
  pr: 82   
  repo: "blobfuse-csi-driver"   
  url: "https://github.com/kubernetes-sigs/blobfuse-csi-driver/pull/82"   
}
```

These are both causing Prow errors that are visible to oncall so please address at your earliest convenience.
/assign @andyzhangx
